/*
 * Charging_Board.h
 *
 *  Created on: 01-May-2024
 *      Author: Lenovo
 */

#ifndef INC_CHARGING_BOARD_H_
#define INC_CHARGING_BOARD_H_

#define CHARGE_OPTION0_LSB 0x00
#define CHARGE_OPTION0_MSB 0x01
#define CHARGE_CURRENT_LSB 0x02
#define CHARGE_CURRENT_MSB 0x03
#define MAX_CHARGE_VOLTAGE_LSB 0x04
#define MAX_CHARGE_VOLTAGE MSB 0x05
#define CHARGE_OPTION1_LSB 0x30
#define CHARGE_OPTION1_MSB 0x31
#define CHARGE_OPTION2_LSB 0x32
#define CHARGE_OPTION2_MSB 0x32
#define CHARGE_OPTION3_LSB 0x34
#define CHARGE_OPTION3_MSB 0x35
#define PROCHOT_OPTION0_LSB 0x36
#define PROCHOT_OPTION0_MSB 0x37
#define PROCHOT_OPTION1_LSB 0x38
#define PROCHOT_OPTION1_MSB 0x39
#define ADC_OPTION_LSB 0x3A
#define ADC_OPTION_MSB 0x3B
#define CHARGER_STATUS_LSB 0x20
#define CHARGER_STATUS_MSB 0x21
#define PROCHOT_STATUS_LSB 0x22
#define PROCHOT_STATUS_MSB 0x23
#define IIN_DPM_LSB 0x24
#define IIN_DPM_MSB 0x25
#define ADCVBUS

#endif /* INC_CHARGING_BOARD_H_ */
